baseurl = "https://angry-meitner-afdd40.netlify.com"
title = "OneOak"

theme = "coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "One.Oak"
    description = "A NEW CONCEPT IN TECHNOLOGY"
    keywords = "one,oak,oneoak,technology"
    info = ""
    avatarurl = "images/avatar.jpg"
    footercontent = ""

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = true

    rtl = false

    # Custom CSS
    custom_css = []



[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = ""

        # You can configure the theme parameter for each language.
        [languages.en.params]
        author = ""
        description = ""
        keywords = "one,oak,oneoak,technology"

        [languages.en.menu] # It is possible to change the menu too.