

name = "Hugo Lime"
license = "MIT"
licenselink = "https://github.com/uicardiodev/hugo-lime/blob/master/LICENSE.md"
description = ""
homepage = ""
tags = ["minimal","blog","services","responsive","bootstrap","uicardio","illustrations"]
features = ["cover","pricing","faq","parteners","blog","work","portfolio","contact","illustrations"]
min_version = "0.47.1"

[author]
  name = "wilber"
  homepage = "https://wilber.co.ke"

[developer]
	name = "Wilber"
	homepage = "https://wilber.co.ke"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""